"""
Evaluation harness for the Minecraft RAG system. Runs the 5 eval questions through ask(),
scores each answer against its ground truth with answer-similarity (cosine of normalized
embeddings, so a dot product), and renders a Markdown report with blank manual-verdict fields.

Run:  python evaluate.py        # writes evaluation_report.md to the project root
"""

from eval_questions import EVAL_SET
from generate import ask
from retrieve import DEFAULT_K
from vectorstore import embed

REPORT_PATH = "evaluation_report.md"


def answer_similarity(answer, ground_truth):
    """Cosine similarity between answer and ground_truth.

    embed() returns L2-normalized vectors, so cosine similarity is the dot product.
    Higher = better (range ~0-1; normalized so the formula allows -1..1).
    Returns 0.0 if either argument is None or empty (no usable text to compare).
    """
    if not answer or not ground_truth:
        return 0.0
    vecs = embed([answer, ground_truth])
    a, b = vecs[0], vecs[1]
    return float(sum(x * y for x, y in zip(a, b)))


def _render_chunk(rank, hit):
    snippet = hit["text"].replace("\n", " ").strip()
    if len(snippet) > 200:
        snippet = snippet[:200] + "..."
    return (f'{rank}. [dist {hit["distance"]:.3f}] {hit["source"]} > {hit["section"]} '
            f'— "{snippet}" ({hit["url"]})')


def _render_result(r):
    chunks = "\n".join(_render_chunk(i, h) for i, h in enumerate(r["hits"], 1))
    return f"""### Q{r['id']} — {r['question']}

**Ground truth:** {r['ground_truth']}

**System answer:** {r['answer']}

**Answer-similarity:** {r['answer_similarity']:.2f}  (higher = better, range 0-1)

**Retrieved chunks** (distance: lower = better, <0.5 = strong):
{chunks}

**Retrieval verdict:** _[ accurate / partial / inaccurate ]_
**Response verdict:** _[ accurate / partial / inaccurate ]_
**Notes:** _____
"""


def to_markdown(results):
    """Render evaluation results as the submission report with blank manual-verdict fields."""
    header = (
        "# Evaluation Report — The Unofficial Minecraft Guide\n\n"
        "Generated by `evaluate.py`. Verdicts and the failure-case analysis are filled in "
        "manually.\n\n"
        "Scores legend:\n"
        "- Answer-similarity: higher = better (range 0-1).\n"
        "- Retrieval distance: lower = better (<0.5 = strong match).\n"
    )
    body = "\n---\n\n".join(_render_result(r) for r in results)
    failure = (
        "\n---\n\n## Failure Case\n\n"
        "_Pick the weakest result above and explain why it failed — e.g. vocabulary mismatch "
        "between the casual question and wiki jargon, a chunk boundary that split the answer, "
        "off-topic retrieval, or a low-similarity answer. Reference the scores as evidence._\n"
    )
    return f"{header}\n---\n\n{body}\n{failure}"
